"""define schema inicial

Revision ID: 666a1395a481
Revises:
Create Date: 2026-09-13 13:15:50.306385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "666a1395a481"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contas",
        "nome",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "contas",
        "saldo",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0.00'"),
    )
    op.alter_column(
        "transacoes", "categoria", existing_type=mysql.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "transacoes",
        "data",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users", "password", existing_type=mysql.TEXT(), type_=sa.String(length=255), nullable=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.alter_column(
        "users", "password", existing_type=sa.String(length=255), type_=mysql.TEXT(), nullable=True
    )
    op.alter_column(
        "transacoes",
        "data",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "transacoes", "categoria", existing_type=mysql.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "contas",
        "saldo",
        existing_type=mysql.DECIMAL(precision=10, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0.00'"),
    )
    op.alter_column(
        "contas",
        "nome",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
