"""adiciona transacoes recorrentes

Revision ID: a92c76962d7f
Revises: 666a1395a481
Create Date: 2026-09-13 13:49:45.246489

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a92c76962d7f"
down_revision: Union[str, Sequence[str], None] = "666a1395a481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transacoes_recorrentes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conta_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.Enum("entrada", "saida"), nullable=False),
        sa.Column("valor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("categoria", sa.String(length=50), nullable=False),
        sa.Column("frequencia", sa.Enum("semanal", "quinzenal", "mensal"), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=False),
        sa.Column("proxima_data", sa.Date(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conta_id"],
            ["contas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ocorrencias_recorrentes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transacao_recorrente_id", sa.Integer(), nullable=False),
        sa.Column("transacao_id", sa.Integer(), nullable=True),
        sa.Column("data_prevista", sa.Date(), nullable=False),
        sa.Column("data_processamento", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("pendente", "realizada", "falhou"), nullable=False),
        sa.Column("motivo_falha", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["transacao_id"],
            ["transacoes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transacao_recorrente_id"],
            ["transacoes_recorrentes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ocorrencias_recorrentes")
    op.drop_table("transacoes_recorrentes")
    # ### end Alembic commands ###
